name: Deploy to Render

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-xxxxxxxxxxxxxxxxxxxx?key=YOUR_RENDER_DEPLOY_KEY